name: Jan Wolanski
favicon: null
layout_spectrum: 0.97364
typography_spectrum: 0.2715383640024811
title: photographer Jan Wolanski blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#c4c7d2'
    - '#323444'
    - '#a69597'
    - '#0e1114'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
