name: Jan Wolanski
favicon: null
layout_spectrum: 0.7270343583077192
typography_spectrum: 0.2715383640024811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8886428375262767
  lightness: 0.27837068377994
  saturation: 0.1850679183844477
  rhythmicContrast: 0.6830428738612682
purpose: []
