typography_spectrum: 0.2715383640024811
color:
  brandColors:
    - '#fdfdfd'
    - '#c4c7d2'
    - '#323444'
    - '#a69597'
    - '#0e1114'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.97364
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jan Wolanski
  url: www.JanWolanski.com
name: Jan Wolanski
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: photographer Jan Wolanski blog
purpose: []
