name: Jan Wolanski
favicon: null
layout_spectrum: 0.4606
typography_spectrum: 0.2715383640024811
title: photographer Jan Wolanski blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2ccd9'
    - '#a4acb7'
    - '#000000'
    - '#748fa4'
    - '#5a6f76'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
